# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
  end
  config.vm.define :master do |master_config|
    master_config.vm.box = "ubuntu/trusty64"
    master_config.vm.host_name = 'saltmaster.local'
    master_config.vm.network "private_network", ip: "192.168.60.10"
    master_config.vm.synced_folder "../state/", "/srv/salt/state"
    master_config.vm.synced_folder "../pillar/", "/srv/salt/pillar"

    master_config.vm.provision :salt do |salt|
      salt.master_config = "saltstack/etc/master"
      salt.minion_config = "saltstack/etc/master_minion"
      grains_config = "saltstack/etc/grains"
      salt.master_key = "saltstack/keys/master_minion.pem"
      salt.master_pub = "saltstack/keys/master_minion.pub"
      salt.minion_key = "saltstack/keys/master_minion.pem"
      salt.minion_pub = "saltstack/keys/master_minion.pub"
      salt.seed_master = {
                          "master" => "saltstack/keys/master_minion.pub",
                          "minion1" => "saltstack/keys/minion1.pub",
                          "minion2" => "saltstack/keys/minion2.pub"
                         }

      salt.bootstrap_script = "saltstack/bootstrap-salt.sh"
      salt.install_type = "stable"
      salt.install_master = true
      salt.verbose = true
      salt.colorize = true
      salt.log_level = "debug"
      salt.run_highstate = false
    end
  end

  config.vm.define :minion1 do |minion_config|
    minion_config.vm.box = "ubuntu/trusty64"
    minion_config.vm.host_name = 'saltminion1.local'
    minion_config.vm.network "private_network", ip: "192.168.60.11"

    minion_config.vm.provision :salt do |salt|
      salt.minion_config = "saltstack/etc/minion1"
      salt.minion_key = "saltstack/keys/minion1.pem"
      salt.minion_pub = "saltstack/keys/minion1.pub"
      salt.bootstrap_script = "saltstack/bootstrap-salt.sh"
      salt.install_type = "stable"
      salt.verbose = true
      salt.colorize = true
      salt.log_level = "debug"
      salt.run_highstate = false
    end
  end

  config.vm.define :minion2 do |minion_config|
    minion_config.vm.box = "ubuntu/trusty64"
    minion_config.vm.host_name = 'saltminion2.local'
    minion_config.vm.network "private_network", ip: "192.168.60.12"

    minion_config.vm.provision :salt do |salt|
      salt.minion_config = "saltstack/etc/minion2"
      salt.minion_key = "saltstack/keys/minion2.pem"
      salt.minion_pub = "saltstack/keys/minion2.pub"
      salt.bootstrap_script = "saltstack/bootstrap-salt.sh"
      salt.install_type = "stable"
      salt.verbose = true
      salt.colorize = true
      salt.log_level = "debug"
      salt.run_highstate = false
    end
  end

end
